### ISSUE TITLE
Setting the terminal character on USBTMCCommunicator results in conversion error

### ISSUE THREAD

**Issue by CatherineH** [Galvant/InstrumentKit#121]
Setting the terminal character on USBTMCCommunicator, i.e.:

```
tek = instruments.tektronix.TekTDS224.open_usbtmc(idVendor=0x0699, idProduct=0x0365)
tek.terminator = '\n'
print(tek.query("WFMPre?"))
```
results in the error:

```
Traceback (most recent call last):
  File "~/InstrumentKit/doc/examples/tektronix/ex_oscilloscope_gui.py", line 13, in <module>
    print(tek.query("WFMPre?"))
  File "~/InstrumentKit/instruments/abstract_instruments/instrument.py", line 132, in query
    value = self._file.query(cmd, size)
  File "~/InstrumentKit/instruments/abstract_instruments/comm/abstract_comm.py", line 233, in query
    resp = self._query(msg, size)
  File "~/InstrumentKit/instruments/abstract_instruments/comm/usbtmc_communicator.py", line 184, in _query
    return self._filelike.ask(msg, num=size, encoding="utf-8")
  File "/usr/local/lib/python2.7/dist-packages/usbtmc/usbtmc.py", line 576, in ask
    return self.read(num, encoding)
  File "/usr/local/lib/python2.7/dist-packages/usbtmc/usbtmc.py", line 559, in read
    return self.read_raw(num).decode(encoding).rstrip('\r\n')
  File "/usr/local/lib/python2.7/dist-packages/usbtmc/usbtmc.py", line 505, in read_raw
    req = self.pack_dev_dep_msg_in_header(read_len, term_char)
  File "/usr/local/lib/python2.7/dist-packages/usbtmc/usbtmc.py", line 436, in pack_dev_dep_msg_in_header
    return hdr+struct.pack("<LBBxx", transfer_size, transfer_attributes, term_char)
struct.error: cannot convert argument to integer
```

I think this has something to do with usbtmc expecting a character or int, and USBTMCCommunicator is providing a str.

**Comment by CatherineH** [comment]
Confirmed: usbtmc requires an integer character. Commenting out these lines in USBTMCCommunicator:

```
'''
        if isinstance(newval, bytes):
            newval = newval.decode("utf-8")
        if not isinstance(newval, str) or len(newval) > 1:
            raise TypeError("Terminator for loopback communicator must be "
                            "specified as a single character string.")
        '''
        self._terminator = newval
        self._filelike.term_char = newval
```

and setting:

```
tek.terminator = 10
```
makes this error go away.
